version = 0.1

[default.deploy.parameters]
stack_name = "hackathon-rag"
resolve_s3 = true
s3_prefix = "hackathon-rag"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "PineconeSecretArn=\"arn:aws:secretsmanager:us-east-1:861164748234:secret:PineconeApiKey-bnQoaH\""
